### ISSUE TITLE
Could not start this game 

### ISSUE THREAD

**Issue by mahmutkocak** [bashbaugh/radar-defense#2]
Hi 

I wanted to try the game but could not start due to the error

Command "python setup.py egg_info" failed with error code 1

like [here.](https://stackoverflow.com/questions/43044636/python-how-to-install-neuralpy/52278899#52278899)

**Comment by bashbaugh** [comment]
How are you running it? It should work with just `python radar-defense.py`. Make sure you are using python2.

**Comment by bashbaugh** [comment]
Also, you need to install PyGame and Shapely with pip for python2, like:

pip install shapely

and 

pip install pygame

**Comment by bashbaugh** [comment]
BE WARNED: This game's graphics are _extremely bad_ right now because I haven't gotten around to making good graphics yet, and this game is _extremely_ simple, plus the instructions are not the best. So don't have high expectations. :unamused:

**Comment by bashbaugh** [comment]
Woops! This game uses python2, use python2, not python3 !
